import { useEffect } from 'react';
import useSWRSubscription from 'swr/subscription';
import { ipc, swrORPC } from '@/renderer/ipc/manager';
import { useUpdateStore } from '@/renderer/store/update';
import { Button } from './ui/Button';

export function Updater() {
  const { status, message, setStatus } = useUpdateStore();

  const { data: updateEvent } = useSWRSubscription(
    // 1. Generate a unique, stable key for the subscription
    swrORPC.app.onUpdateStatus.key({}),
    // 2. Provide the subscriber function generated by the oRPC SWR utility
    swrORPC.app.onUpdateStatus.liveSubscriber({}), // 2. Use liveSubscriber for the latest event
  );

  // 3. Use an effect to synchronize the data received from the subscription
  //    with our central Zustand store.
  useEffect(() => {
    if (updateEvent) {
      setStatus(updateEvent.status, updateEvent.message);
    }
  }, [updateEvent, setStatus]);

  const handleCheckForUpdates = () => {
    // Set status immediately for better UX, even before the event arrives.
    setStatus('checking');
    ipc.client.app.checkForUpdates();
  };

  const handleRestartAndInstall = () => {
    ipc.client.app.restartAndInstall();
  };

  // When the app is up to date, show the message for a few seconds then revert to idle.
  useEffect(() => {
    if (status === 'not-available') {
      const timer = setTimeout(() => {
        setStatus('idle');
      }, 3000);
      return () => clearTimeout(timer);
    }
  }, [status, setStatus]);

  switch (status) {
    case 'checking':
      return <p className="text-sm text-muted-foreground">Checking for updates...</p>;
    case 'available':
      return <p className="text-sm text-muted-foreground">Update available, downloading...</p>;
    case 'downloaded':
      return (
        <div className="flex items-center space-x-2">
          <p className="text-sm">Update ready.</p>
          <Button onClick={handleRestartAndInstall} size="sm">
            Restart & Install
          </Button>
        </div>
      );
    case 'not-available':
      return <p className="text-sm text-green-600">You are up to date!</p>;
    case 'error':
      return (
        <div className="flex items-center space-x-2">
          <p className="text-sm text-red-600" title={message}>
            Update failed.
          </p>
          <Button onClick={handleCheckForUpdates} variant="outline" size="sm">
            Try Again
          </Button>
        </div>
      );
    case 'idle':
    default:
      return (
        <Button onClick={handleCheckForUpdates} variant="outline" size="sm">
          Check for Updates
        </Button>
      );
  }
}
